spring.application.name=online-book-reading-platform

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/book_reading_platform
spring.datasource.username=root
spring.datasource.password=${LOCAL_DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

jwt.secret=${LOCAL_JWT_SECRET:localdevsecretonlyfordevtestingpurpose12345}
jwt.expiration-ms=86400000


#spring.application.name=online-book-reading-platform
#
#server.port=8081
#
#spring.datasource.url=jdbc:mysql://localhost:3306/book_reading_platform
#spring.datasource.username=root
#spring.datasource.password=Vicky098@
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#
#jwt.secret=bb115783d6fc8ff8aa8c0831b046310068fc6936d0dc6f8364087b916c0cfe63
#jwt.expiration-ms=86400000